### ISSUE TITLE
Proxy Protocol not Working on UDP Traffic

### ISSUE THREAD

**Issue by G5Hg3EmMa9ss97** [zhboner/realm#88]
Hi,

It seems that proxy protocol header doesn't send properly when forwarding UDP traffic. I ran realm using `realm -l 0.0.0.0:102 -r remote-ip:102 --udp --send-proxy` command.

On the remote server, client IP and port can be obtained only in TCP traffic. Can you please confirm whether this is expected? Thanks.

**Comment by zephyrchien** [comment]
Yes, this is expected behavior. Proxy Protocol is mainly designed for TCP, the spec does not include details about UDP. Its inventor, Haproxy, known as TCP load balancer, does not support UDP either.

It seems some proxies do support UDP Proxy Protocol, such as Nginx, [Cloudflare's Spectrum](https://developers.cloudflare.com/spectrum/how-to/enable-proxy-protocol/#enabling-proxy-protocol-v2-for-tcpudp). They prepend the PROXY header to the first packet on a stream(packets from the same source). I will consider adding this feature with the same approach though, as [this comment](https://trac.nginx.org/nginx/ticket/1543#comment:1) said, It might not be a good idea.
